[wokwi]
version = 1
firmware = '../.pio/build/wokwi_sim/firmware.bin'
elf = '../.pio/build/wokwi_sim/firmware.elf'

[network]
ssid = "Wokwi-GUEST"
password = ""

[flash]
fs = "../.pio/build/wokwi_sim/littlefs.bin"

[[chip]]
name = "bme280"
binary = "bme280.chip.wasm"